telegram_analytics:
  target: sqlite
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'password') }}"
      port: "{{ env_var('DB_PORT', 5432) | int }}"
      dbname: "{{ env_var('DB_NAME', 'telegram_warehouse') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      search_path: "public"
    
    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      user: "{{ env_var('PROD_DB_USER') }}"
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      port: "{{ env_var('PROD_DB_PORT', 5432) | int }}"
      dbname: "{{ env_var('PROD_DB_NAME') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      search_path: "public"
    
    # SQLite configuration for local development
    sqlite:
      type: sqlite
      database: "../telegram_data.db"
      schema: main
      schema_directory: "../"
      schemas_and_paths:
        main: "../telegram_data.db"
      threads: 1