version: 2

sources:
  - name: telegram_data
    description: "Raw data from Telegram scraping"
    tables:
      - name: telegram_channels
        description: "Telegram channel information"
        columns:
          - name: id
            description: "Primary key for channels"
            tests:
              - unique
              - not_null
          - name: username
            description: "Channel username"
            tests:
              - not_null
          - name: title
            description: "Channel display title"
          - name: about
            description: "Channel description"
          - name: participants_count
            description: "Number of channel participants"
          - name: is_broadcast
            description: "Whether the channel is a broadcast channel"
          - name: is_megagroup
            description: "Whether the channel is a megagroup"
          - name: created_date
            description: "When the channel was created"
          - name: scraped_at
            description: "When the channel was scraped"

      - name: telegram_messages
        description: "Messages scraped from Telegram channels"
        columns:
          - name: id
            description: "Primary key for messages"
            tests:
              - not_null
          - name: channel_username
            description: "Foreign key to telegram_channels"
            tests:
              - not_null
              - relationships:
                  to: source('telegram_data', 'telegram_channels')
                  field: username
          - name: date
            description: "When the message was posted"
            tests:
              - not_null
          - name: text
            description: "Text content of the message"
          - name: sender_id
            description: "ID of the message sender"
          - name: sender_username
            description: "Username of the message sender"
          - name: sender_first_name
            description: "First name of the message sender"
          - name: sender_last_name
            description: "Last name of the message sender"
          - name: views
            description: "Number of views"
          - name: forwards
            description: "Number of forwards"
          - name: replies
            description: "Number of replies"
          - name: is_reply
            description: "Whether this message is a reply"
          - name: reply_to_msg_id
            description: "ID of the message this replies to"
          - name: has_media
            description: "Whether the message contains media"
          - name: media_type
            description: "Type of media attached"
          - name: media_file_path
            description: "Path to the media file"
          - name: raw_data
            description: "Raw message data in JSON format"

      - name: media_files
        description: "Media files downloaded from messages"
        columns:
          - name: id
            description: "Primary key for media files"
            tests:
              - unique
              - not_null
          - name: channel_username
            description: "Channel username"
            tests:
              - not_null
          - name: message_id
            description: "Foreign key to telegram_messages"
            tests:
              - not_null
          - name: file_path
            description: "Path to the downloaded file"
          - name: media_type
            description: "Type of media file"
          - name: file_size
            description: "Size of the file in bytes"
          - name: created_at
            description: "When the record was created"

      - name: business_info
        description: "Business information extracted from messages"
        columns:
          - name: id
            description: "Primary key for business info"
            tests:
              - unique
              - not_null
          - name: channel_username
            description: "Channel username"
            tests:
              - not_null
          - name: message_id
            description: "Foreign key to telegram_messages"
            tests:
              - not_null
          - name: business_name
            description: "Extracted business name"
          - name: phone_number
            description: "Extracted phone number"
          - name: service_type
            description: "Type of service offered"
          - name: location
            description: "Business location"
          - name: extracted_at
            description: "When the information was extracted"

      - name: detected_objects
        description: "Objects detected by YOLO in media files"
        columns:
          - name: id
            description: "Primary key for detected objects"
            tests:
              - unique
              - not_null
          - name: message_id
            description: "Foreign key to telegram_messages"
            tests:
              - not_null
          - name: media_file_id
            description: "Foreign key to media_files"
            tests:
              - not_null
              - relationships:
                  to: source('telegram_data', 'media_files')
                  field: id
          - name: object_class
            description: "Class of the detected object"
          - name: confidence
            description: "Confidence score of the detection"
          - name: bbox_x
            description: "X coordinate of bounding box"
          - name: bbox_y
            description: "Y coordinate of bounding box"
          - name: bbox_width
            description: "Width of bounding box"
          - name: bbox_height
            description: "Height of bounding box"
          - name: created_at
            description: "When the detection was performed"